---
title: "Correlation Matrix"
author: "Connor"
date: "5/19/2023"
output: html_document
---

Load Packages and Libraries
What are packages?
What are libraries?
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(ggcorrplot)
library(plotly)
```

Read in the data
read_csv is a function from the tidyverse package
also import button option

```{r}
dataset <- read_csv(here("data/nd-gain-data/joined_data/nd-gain-joined.csv"))
```

Round decimals in the value column
```{r}
dataset$value <- round(dataset$value, digits = 2)
```


Explain Pipe 

```{r}
dataset <- dataset %>% 
  filter(year == 2020)
```

Drop NA's of the dataset
```{r}
dataset <- drop_na(dataset)
```

```{r}
dataset <- dataset %>% 
  pivot_wider(names_from = indicator, 
              values_from = value)
  
```

```{r}
dataset <- dataset %>% 
  select(-ISO3, -year, -Name)
```

```{r}
dataset <- dataset %>%
  mutate(sids_context = ifelse(sids_context == "non-sids", 0, 1))
```

```{r}
cor_matrix <- cor(dataset[complete.cases(dataset), ], use = "pairwise.complete.obs")
```

```{r}
corrplot <- ggcorrplot(cor_matrix, type = "lower", outline.color = "white") +
  theme(axis.text.x = element_text(size = 3),
        axis.text.y = element_text(size = 3))
```

```{r}
ggplotly(corrplot)
```

